import type {Metadata} from "next";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {Poppins} from "next/font/google"
import {Toaster} from "sonner";

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-poppins',
    fallback: ['sans-serif']
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning className={poppins.className}>
        <body
            className={`antialiased`}
        >
        <ThemeProvider
            attribute={"class"}
            defaultTheme={"system"}
            enableSystem
            storageKey={"theme"}
            disableTransitionOnChange
        >
            {children}
            <Toaster position={"top-right"} richColors/>
        </ThemeProvider>
        </body>
        </html>
    );
}
