import type {Metadata} from "next";
import "./globals.css";
import {Poppins} from "next/font/google"
import Providers from "@/app/providers";

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-poppins',
    fallback: ['sans-serif']
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning className={poppins.className}>
        <body
            className={`antialiased`}
        >
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}
